CREATE TABLE colaborador (
  ID_COLABORADOR INT NOT NULL,
  NOME VARCHAR(45),
  CPF VARCHAR(45),
  IND_OPCOES_CB INT,		
  PRIMARY KEY (ID_COLABORADOR),
  CONSTRAINT fk_colab FOREIGN KEY (IND_OPCOES_CB) REFERENCES opcao (IND_OPCOES_CB)
);

CREATE TABLE opcao (
  IND_OPCOES_CB INT NOT NULL,
  NOME VARCHAR(45),
  IND_TIPO_OPCAO INT,
  PRIMARY KEY (IND_OPCOES_CB)
);
